name: Flatpak on Ubuntu 22.04 platforms

permissions:
  contents: write
  discussions: write

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
#        https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        arch: [x86_64]
        os: [ubuntu-22.04]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Look OS information
      run: |
        cat /etc/os-release

    - name: Flatpak Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ok-msg.flatpak
        manifest-path: flatpak/org.okstar.ok-msg.yml
        cache-key: flatpak-builder-${{ github.sha }}